[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/neacsu/cosmos-rust"]
git = "https://github.com/neacsu/cosmos-rust"
branch = "neacsu/feegrant_support"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "./vendor"